#!/bin/bash
#PBS -l nodes=32:ppn=32:xe
#PBS -l walltime=10:00:00
#PBS -N RAVEN_DEP
#PBS -j oe   

### cd to the location where you submitted the job, if needed
### note that you are on a PBS MOM node and not running interactively on a
### compute node

cd $PBS_O_WORKDIR

# To add certain modules that you do not have added via ~/.modules
module swap PrgEnv-cray PrgEnv-gnu
export OMP_NUM_THREADS=32

aprun -n 32 -d 32 bwpy-environ $ravenpy dep_rom_input.xml

